name: Populate PR Description
on:
  pull_request:
    types:
      - opened
jobs:
  populateDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Update pull request
        uses: kt3k/update-pr-description@v1.0.0
        with:
          pr_body: "Description of the PR"
          github_token: ${{ secrets.GITHUB_TOKEN }}
