name: Populate PR Description
on:
  pull_request:
    types:
      - opened
jobs:
  populateDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: update-pull-request
        uses: kt3k/update-pr-description@v1.0.0
        with:
          pr_body: "**some description**"
          github_token: ${{ secrets.GITHUB_TOKEN }}
