name: Populate PR Description
on: pull_request
jobs:
  populateDescription:
    runs-on: ubuntu-latest
    steps:
      - run : echo
      - name: update-pull-request
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: "${{ github.base_ref }}"
          head-branch-regex:  "${{ github.head_ref }}"
          title-template: '[%headbranch%] '
          body-template: |
            Merging into '%basebranch%'
            [Link to %headbranch%](https://url/to/browse/ticket/%headbranch%)
          body-update-action: 'suffix'
          body-uppercase-base-match: false
