name: Populate PR Description
on:
  pull_request:
    types:
      - opened
jobs:
  populateDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: |
            echo "$GITHUB_CONTEXT"
            echo ${{ github.event.pull_request.title }}
      - name: update-pull-request
        uses: kt3k/update-pr-description@v1.0.0
        with:
          pr_body: "**some description**"
          github_token: ${{ secrets.GITHUB_TOKEN }}
